---
title: "Use-DAT"
output: html_document
editor_options: 
  chunk_output_type: console
---

Data from https://www.spc.noaa.gov/wcm/

```{r}
df <- read.csv("2014-2015-onetor-dat.csv")

ii <- which(is.na(df$path_data) & is.na(df$point_data))
df$path_data[ii] <- 1
```

```{r}
library(dplyr)

df1 <- df %>%
  filter(path_data == 1) %>%
  select(unique_torID, om:mt)

df2 <- df %>%
  filter(point_data == 1) %>%
  select(unique_torID, OBJECTID:edit_time.1)

dfFinal <- left_join(df2, df1, 
                     by = "unique_torID")
```

Create a simple feature data frame and set and then transform the CRS.
```{r}
dfFinal <- dfFinal %>%
  filter(!is.na(lat))

library(sf)
projcrs <- 4326
sfdf <- st_as_sf(x = dfFinal,                         
                 coords = c("lon", "lat"),
                 crs = projcrs) %>%
  st_transform(crs = 102008)
```

```{r}
ids <- unique(sfdf$om)
sfdf2 <- sfdf %>%
  filter(om == ids[5]) %>%
  mutate(EF = as.integer(efscale.1))

table(sfdf2$EF)

sfdf2 <- sfdf %>%
  filter(unique_torID == 72) %>%
  mutate(EF = as.integer(efscale.1))
```

Convert to buffered line string.
```{r}
MP <- st_combine(sfdf2)
LS <- st_sfc(st_linestring(st_coordinates(MP)), crs = 102008)
BLS <- st_buffer(LS, dist = 500)
```

```{r}
library(tmap)
library(USAboundaries)

ctys <- us_counties() 

tm_shape(BLS) +
  tm_polygons() +
tm_shape(LS) +
  tm_lines() +
tm_shape(ctys) +
  tm_borders()

```

Perhaps do this for each EF rating?
```{r}
path <- st_convex_hull(st_combine(sfdf2))

tm_shape(path2) +
  tm_polygons(alpha = .3) +
tm_shape(path) +
  tm_polygons(alpha = .3) +
tm_shape(sfdf2) +
  tm_bubbles(size = 1) +
tm_shape(ctys) +
  tm_borders()
```